# Generated by Django 4.0.6 on 2022-07-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_remove_user_personel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roll',
            field=models.CharField(choices=[('master', 'master'), ('student', 'student')], max_length=255, null=True),
        ),
    ]
